apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: npxyq551q-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: npxyq551q-go 
  name: npxyq551q-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: npxyq551q-go 
