apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: npxyq551q-go 
  janus-idp.io/tekton: npxyq551q-go
  backstage.io/kubernetes-id: npxyq551q-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: npxyq551q-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml